#soal latihan mencetak nama sendiri pada python
print('perymerdeka')

#soal latihan mencetak lirik lagu ke layar
print(" KIMI DATTARA    ")
print("zutto shikatta koto wa tsuini")
print("kimi to wa dekinai mama tou tou owarimashita")
print('Hizuke ga kawaru koro ni te wo tsunaide konbini e aruku')
print('watashi no tonari chigau hito ga iru yo')
print('\n')
print('aishiteru to iware te mo kimi janai kara')
print('watashi wa jouzou ni warau koto ga dekinai')
print('ichi do mo sono kotoba wo kuchi ni shi nakatta kimi wo kimi wo')
print('watashi wa wa wazurerarezu ni iru yo')
print('\n')
print('attarashi koibito to dakiate iru toki mo')
print('kisu wo shi te iru toki demo kimi wo omoidasu kara')
print('\n')
print('kimi dattara kimi dattara')
print('ima koko ni iru no da')
print('kimi dattara kimi dattara')
print('dinnani yokatta ka')
print('\n')
print('kimi dattara kimi dattara')
print('watashi washiawase datta noni')
print('sonna koto bakari kangae te shimau')
print('\n')
print('kimi dattara kimi dattara')
print('ima koko ni iru no da')
print('kimi dattara kimi dattara')
print('donnani yokatta ka')
print('\n')
print('kimi dattara kimi dattara')
print('nan demo aiseta noni na')
print('sonna koto bakari kangaete')
print('\n')
print('kimi dattara kimi dattara')
print('ima koko ni iru no da')
print('kimi dattara kimi dattara')
print('atashi washiawase datta noni')
print('\n')
print('kimi dattara kimi dattara')
print('nan demo aise ta noni na')
print('sonna koto bakari kangaete shimau')